In [ ]:
# Numpy --> Numerical Python
import numpy as np
print(np.__version__)

2.0.2


In [ ]:
# Numpy provides support for most powerful data structure -- array
arr = np.array([10,20,30,40,50,60])
print(arr)
print(type(arr))

[10 20 30 40 50 60]
<class 'numpy.ndarray'>


In [ ]:
# Python List vs Numpy

# how much execution time will be taken by List and sum()

import time
numbers = __builtins__.list(range(1,100000001))
total = 0
start_time = time.time()    # record start time
for i in numbers:
  total = total + i
end_time = time.time()     # record end time
print('Total :', total)
print("Execution Time : ",end_time - start_time,"seconds")
print(f"Execution Time : {end_time - start_time:.4f} seconds")
#.4f means show 4 digits after the decimal point

Total : 5000000050000000
Execution Time :  14.598828077316284 seconds
Execution Time : 14.5988 seconds


In [ ]:
numbers = np.arange(1,100000001)
total = 0
start_time = time.time()  # record start time
total = np.sum(numbers)
end_time = time.time()  # record end time
print("Total : ",total)
print("Execution Time : ",end_time - start_time,"seconds")
print(f"Execution Time : {end_time - start_time:.4f} seconds")

Total :  5000000050000000
Execution Time :  0.0691375732421875 seconds
Execution Time : 0.0691 seconds


In [ ]:
# array()
# In programming an array is a data structure used to store collection of data values

# Array : Single Dimension (1D) and Multi Dimensional (2D)

# How to create an array(1D)
arr = np.array([10,20,30,40,50,60])
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[10 20 30 40 50 60]


In [ ]:
# An array is a collection of similar Data Type
emp_info = np.array([123, 'Ash', 89.31, True])
print(emp_info)

['123' 'Ash' '89.31' 'True']


In [ ]:
# Shape property
# used to determine the dimensions of an array
# For 1D array return (n,) --> where n is the number of elements
# For 2D array return (n,m) --> where n is the number of rows and m is the number of columns

arr = np.array([10,20,30,40,50,60])
print(arr.shape)

(6,)


In [ ]:
# 2D Array
arr = np. array([[1,2,3], [3,4,5], [5,6, 7]])
print (arr. shape)
print (arr)

# Tip for 2D Array
# np.array([])
# 3x3 matrix

# Create a 2X5 Matrix
arr = np. array([[1,2,3,4,5], [6,7,8,9,0]])

# Create a 4X3 Matrix
arr = np. array([[1,2,3], [3,4,5], [5,6, 7], [8,9,0]])

(3, 3)
[[1 2 3]
 [3 4 5]
 [5 6 7]]


In [ ]:
# Indexing And Slicing
arr = np. array([10,20, 30,40, 50, 60])

# 10   20   30   40   50   60
# 0    1     2   3    4    5
# -6   -5  -4    -3  -2   -1

print(arr)
print(arr[-1])
print(arr[3])
print(arr[1:5])
print(arr[::-1])

[10 20 30 40 50 60]
60
40
[20 30 40 50]
[60 50 40 30 20 10]


In [ ]:
arr = np. array([[1,2,3], [4,5,6], [7,8,9]])
print(arr)
print(arr[1,1])  # show me the element which exist at r1 and c1
print(arr[2,2])

# show me the first row only
print(arr[0])

# show me the second column only     FOR COLUMN USE THE SYNTAX [:,COLUMN_INDEX_NUMBER]
print(arr[:,1])
print(arr[:,1:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
5
9
[1 2 3]
[2 5 8]
[[2 3]
 [5 6]
 [8 9]]


In [ ]:
# Numpy data type
arr = np.array([10,20,30,40])
print(arr.dtype)
# dtype property helps us to determine the data type of an array

int64


In [ ]:
arr = np.array([10.1,20.2,30.3,40.4])
print(arr.dtype)

float64


In [ ]:
arr = np.array([True,False,False,True])
print(arr.dtype)

bool


In [ ]:
arr = np.array(['A', 'B', 'C', 'D'])
print(arr.dtype)

<U1


In [ ]:
arr = np.array(['Python', 'Ashley Thomas', 'C', 'D'])
print(arr.dtype)

<U13


In [ ]:
# we can also use dtype for Conversion

arr = np.array([10,20,30, 40])
print (arr.dtype)
print(arr.nbytes) # total bytes used by an array

# this int64 means 64 Bits
# meaning each and every individual element of an array can take upto 64 bits
# we have 4 elements
# 4 * 64 Bits --> Total Size Of Arr : 256 bits
# and if we convert it into bytes 4 element * 8 bytes : 32 gutes

int64
32


In [ ]:
# we can also use dtype for Conversion
arr = np.array([10,20,30,40])
print(arr.dtype)
print(arr.nbytes) # total bytes used by an array

# this int64 means 64 Bits
# meaning each and every individual element of an array can take upto 64 bits
# we have 4 elements
# 4 * 64 Bits --> Total Size Of Arr : 256 bits
# and if we convert it into bytes  4 element * 8 bytes  : 32 bytes


# behind the scene each and every individual element will gonna take 64 digits space

# 6bits 6*4 ==> 24 bits
#  Total Size Of Arr :24 bits

int64
32


In [ ]:
arr = np.array([10,20,30,40], dtype = 'i1')
print(arr.dtype)
print(arr.nbytes)

# this int8 means 8 Bits
# meaning each and every individual element of an array can take upto 8 bits
# we have 4 elements
# 4 * 8 Bits --> Total Size Of Arr : 32 bits
# and if we convert it into bytes  4 element * 1 bytes  : 4 bytes

# behind the scene each and every individual element will gonna take 8 digits space


# when in an array you are storing the age or marks

int8
4


In [ ]:
age = np.array([34,78,56,21,90,100,120,17],dtype='i4')
print(age.dtype)
print(age.nbytes)

# i1 --> 8 digits space
# i2 --> 16 digits space
# i4 --> 32 digits space
# i8 --> 64 digits space

int32
32


In [ ]:
a = np.array([10.,20.,30.,40.,50.],dtype='f')
print(a)
print(a.dtype)

[10. 20. 30. 40. 50.]
float32


In [ ]:
a = np.array([10.,20.,30.,40.,50.],dtype='i')
print(a)
print(a.dtype)

[10 20 30 40 50]
int32


In [ ]:
# astype() used for conversions
arr = np.array([10.,20.,30.,40.,50.])
arr = arr.astype('i8')
print(arr.dtype)

int64


In [ ]:
# copy() vs view() method of numpy

# copy()
# a copy will create a new independent array in a different memory location

org_array = np.array([1,2,3,4,5,6])
print(org_array)

copied_array = org_array.copy()
print(copied_array)

# if we make any changes in copied array, it wont effect the original array
copied_array[0] = 100
print(copied_array)
print(org_array)

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[100   2   3   4   5   6]
[1 2 3 4 5 6]


In [ ]:
# View()
# a view is the representation of the original array

org_array = np.array([1,2,3,4,5,6])
print(org_array)

copied_arr = org_array.view()
print(copied_arr)

# if we make any changes in copied array, it will effect the original array
copied_arr[0] = 100
print(copied_arr)
print(org_array)

# if we make any changes in org array, it will effect the copied array
org_array[4] = 400
print(org_array)
print(copied_arr)

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[100   2   3   4   5   6]
[100   2   3   4   5   6]
[100   2   3   4 400   6]
[100   2   3   4 400   6]


In [ ]:
org_array = np.array([1,2,3,4,5,6])
copied_arr = org_array.view()

# shares_memory() --> return True if arrays are sharing the same memory location

print(np.shares_memory(org_array,copied_arr))

True


In [ ]:
# Numpy Array Reshaping
# Converting 1D into 2D or converting 2D into 1D
# reshape()

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr.shape) # 2x6 3x4 4x3 6x2 12x1 1x12

arr = arr.reshape(3,4)
print(arr)
print(arr.shape)

(12,)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [ ]:
# numpy.newaxis is used to increase the dimension of the existing array by one more dimension
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13])
# arr[:,np.newaxis]            Column Vector
arr = arr[np.newaxis,:]      # Row Vector
print(arr.shape)

(1, 13)


In [ ]:
# Converting 2D to 1D

twod = np.array([[1,2],[3,4],[5,6]])
print(twod.shape)
arr = twod.reshape(6)
print(arr)

(3, 2)
[1 2 3 4 5 6]


In [ ]:
twod = np.array([[1,2],[3,4],[5,6]])
print(twod.shape)
arr = twod.reshape(-1)
print(arr)

(3, 2)
[1 2 3 4 5 6]


In [ ]:
twod = np.array([[1,2],[3,4],[5,6]])
print(twod.shape)
arr = twod.flatten()
print(arr)

(3, 2)
[1 2 3 4 5 6]


In [ ]:
# concatenate()
# used to join 2 arrays

pp1 = np.array([20,60,80,45,32])
pp2 = np.array([10,20,30,40,50,67,32,90])
pp3 = np.array([100,200,300,400])
arr = np.concatenate((pp1,pp2,pp3))
print(arr)

[ 20  60  80  45  32  10  20  30  40  50  67  32  90 100 200 300 400]


In [ ]:
t1 = np.array([[1,2],[3,4]])
t2 = np.array([[5,6],[7,8],[9,10]])
arr = np.concatenate((t1,t2))
print(arr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [ ]:
# array_splits()
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
arr = np.array_split(arr,3)
print(arr[0])
print(arr[1])
print(arr[2])

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [ ]:
# sorting
# np.sort() by default it will sort in an ascending order

prices = np.array([100,20,3,30,90,100,11,12])
print(np.sort(prices))

[  3  11  12  20  30  90 100 100]


In [ ]:
prices = np.array([100,20,3,30,90,100,11,12])
print(np.sort(prices)[::-1]) # descending order

[100 100  90  30  20  12  11   3]


In [ ]:
# Filter and searching in an array
prices = np.array([100,20,3,30,90,100,11,88,98,45])
print(prices)
for i in prices:
  if i >=50:
    print(i)

[100  20   3  30  90 100  11  88  98  45]
100
90
100
88
98


In [ ]:
prices = np.array([100,20,3,30,90,100,11,88,98,45])
# Boolean Masking
prices>=50

array([ True, False, False, False,  True,  True, False,  True,  True,
       False])

In [ ]:
prices = np.array([100,20,3,30,90,100,11,88,98,45])
# Boolean Masking
newarr = prices[prices>=50] # here we are appling a filter prices[showMeOnlyTrueValue]
print(newarr)

[100  90 100  88  98]


In [ ]:
prices = np.array([100,20,3,30,90,100,11,88,98,45])
# show the even number prices
newarr = prices[prices%2==0]
print(newarr)

[100  20  30  90 100  88  98]


In [ ]:
prices = np.array([100,20,3,30,90,100,11,88,98,45])
# np.where(expression)
# np.where returns INDEX NUMBERS
res = np.where(prices%2==0)
print(prices[res])

[100  20  30  90 100  88  98]


In [ ]:
prices = np.array([100,20,3,30,90,100,11,88,98,45])
res = np.where((prices%2==0) & (prices>=50))
print(prices[res])
# & combines both condition

[100  90 100  88  98]


In [ ]:
prices = np.array([100,20,3,30,90,100,11,88,98,45])
print(prices[(prices%2==0) & (prices>=50)])

[100  90 100  88  98]


In [ ]:
# SALARY CLASSIFICATION
salary = np.array([25000, 40000, 55000, 70000, 30000, 90000])
# Replace salary with High if salary >= 60000
# Replace salary with Medium if salary >= 40000 and <= 60000
# Otherwise Low

# np.where(condition,value_if_true,value_if_false)

result = np.where(
    salary >= 60000 , "High" ,
    np.where(salary >=40000 , "Medium" ,"Low")
)

print(result)

['Low' 'Medium' 'Medium' 'High' 'Low' 'High']


In [ ]:
# Numpy Random Module
from numpy import random
x = random.randint(100)  # 1 till 100
print(x)

97


In [ ]:
x = random.randint(100,150)  # 100 till 150
print(x)

113


In [ ]:
# rand() generate random float
# method returns a random float value between 0 and 1

print(random.rand())

0.33963233644504986


In [ ]:
# generating 1D Array
arr = random.randint(30,120,size=(5)) # size means dimensions of an array
print(arr)

[89 74 33 91 70]


In [ ]:
# generating 2D Array
arr = random.randint(30,120,size=(3,4)) # size means dimensions of an array
print(arr)

[[ 39 104 106  94]
 [ 40 112  73  56]
 [ 54  76 103  43]]


In [ ]:
arr = random.rand(10)
print(arr)

[0.12853325 0.95691369 0.66175885 0.94222676 0.82214808 0.90142225
 0.55714519 0.85938145 0.71334808 0.08726198]


In [ ]:
arr = random.rand(5,4)
print(arr)

[[0.75891862 0.38410045 0.93526816 0.86904176]
 [0.28335752 0.67996954 0.3219673  0.81564588]
 [0.58097803 0.81588834 0.33124299 0.11404481]
 [0.73533515 0.96012748 0.80391454 0.37654515]
 [0.36990485 0.61994829 0.87488315 0.6012634 ]]


In [ ]:
# choice() method allows you to generate a random value
# based on an array of values

arr = random.choice([10,20,30,40,50,60])
print(arr)

40


In [ ]:
arr = random.choice([10,20,30,40,50,60],size=(7))
print(arr)

[30 20 50 20 60 30 30]


In [ ]:
arr = random.choice([10,20,30,40,50,60],size=(3,4))
print(arr)

[[50 40 10 40]
 [50 20 40 50]
 [50 50 10 60]]


In [ ]:
# numpy.zeros()
# this methods allow us to create an array filled with zero
# default data type will be float

x = np.zeros(7)
print(x)

[0. 0. 0. 0. 0. 0. 0.]


In [ ]:
x = np.zeros((3,3),dtype='i')
print(x)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
# numpy.ones()
# this methods allow us to create an array filled with ones
# default data type will be float

x = np.ones(7)
print(x)

[1. 1. 1. 1. 1. 1. 1.]


In [ ]:
x = np.ones((3,3),dtype='i')
print(x)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
# numpy.sum()
# use to compute the sum of all element

x = np.random.randint(50,size=(120))
print(x)

[48 40 15 49 14 49 35 43 37 11 37 15 46 10 14  6  1 38 15 49 14 40 11 37
 49 41  4 31 17 26 30 30  0 14 31 32 39 37 16 39 38 28  3 43  8 43 37 49
 37 42 32 41 38 37 49 29 41 44 11 24 16 33 26 25 13 26 27 30 22 29  1  4
  8 26 46 13 11 24 15 22 14  0 21 18 28 23 40 28 13 33 13 42 43 13 37 32
 36 19 29 49 23 45 45 18 46 34 34  4 39 14 40 17  3  7 20 44 18  2  8 36]


In [ ]:
print('Sum of An Array')
print(np.sum(x))

Sum of An Array
3229


In [ ]:
# numpy.mean()
# mean value is the average value
print('Mean of An Array')
print(np.mean(x))

Mean of An Array
26.908333333333335


In [ ]:
print('Min of An Array')
print(np.min(x))
print('Max of An Array')
print(np.max(x))

Min of An Array
0
Max of An Array
49


In [ ]:
# Most asked question

# numpy.unique()
# return unique elements as a sorted array

a = np.array([1,2,3,11,4,10,9,12,5,6,1,4,3,2,5,6,7,8,9,2,3,4,5,7,1])
print(np.unique(a))

# 2 3 11 4 10 9 12 5 6 78

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
a = np.array([1,2,3,11,4,10,9,12,5,6,1,4,3,2,5,6,7,8,9,2,3,4,5,7,1])
uv, i = np.unique(a,return_index=True)
print(uv)
print(i)
# return_index --> it will print the index numbers

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 0  1  2  4  8  9 16 17  6  5  3  7]


In [ ]:
# argsort --> reorder the index numbers in a proper sequence
uv[np.argsort(i)]

array([ 1,  2,  3, 11,  4, 10,  9, 12,  5,  6,  7,  8])

In [ ]:
a = np.array([1,2,3,11,4,10,9,12,5,6,1,4,3,2,5,6,7,8,9,2,3,4,5,7,1])
uv, i = np.unique(a,return_index=True)
uv[np.argsort(i)]

array([ 1,  2,  3, 11,  4, 10,  9, 12,  5,  6,  7,  8])

In [ ]:
# arange()
print(np.arange(10))
print(np.arange(1,11))
print(np.arange(1,11,2))

[0 1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


In [ ]:
# Numpy Broadcasting (commonly asked iv question)
arr1 = np.array([1,2,3])
arr2 = np.array([10,20,30])
print(arr1 + arr2)
print(arr1*arr2)

[11 22 33]
[10 40 90]


In [ ]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([10,20,30])
print(arr1 + arr2)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [ ]:
# in which cases there will be no broadcasting error
# case 1 : when arrays are equal
# case 2 : if anyone of them is 1

arr1 = np.array([16,24,26])
arr2 = np.array([2])    # 2 2 2
print(arr1+arr2)

[18 26 28]
